//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CelesteStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ws://localhost:8000/vnyan")]
        public string VNyanURL {
            get {
                return ((string)(this["VNyanURL"]));
            }
            set {
                this["VNyanURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VTuberDangerZoneX1 {
            get {
                return ((int)(this["VTuberDangerZoneX1"]));
            }
            set {
                this["VTuberDangerZoneX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("136")]
        public int VTuberDangerZoneY1 {
            get {
                return ((int)(this["VTuberDangerZoneY1"]));
            }
            set {
                this["VTuberDangerZoneY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int VTuberDangerZoneX2 {
            get {
                return ((int)(this["VTuberDangerZoneX2"]));
            }
            set {
                this["VTuberDangerZoneX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int VTuberDangerZoneY2 {
            get {
                return ((int)(this["VTuberDangerZoneY2"]));
            }
            set {
                this["VTuberDangerZoneY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VTuberSafeZoneX1 {
            get {
                return ((int)(this["VTuberSafeZoneX1"]));
            }
            set {
                this["VTuberSafeZoneX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104")]
        public int VTuberSafeZoneY1 {
            get {
                return ((int)(this["VTuberSafeZoneY1"]));
            }
            set {
                this["VTuberSafeZoneY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int VTuberSafeZoneX2 {
            get {
                return ((int)(this["VTuberSafeZoneX2"]));
            }
            set {
                this["VTuberSafeZoneX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int VTuberSafeZoneY2 {
            get {
                return ((int)(this["VTuberSafeZoneY2"]));
            }
            set {
                this["VTuberSafeZoneY2"] = value;
            }
        }
    }
}
